
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bxeofnizgwsyddwkborh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4ZW9mbml6Z3dzeWRkd2tib3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzMxNTQsImV4cCI6MjA2MTE0OTE1NH0.ABJYC_Xb-rtVc1vv2Jbi3V-psk-cBJfL-l0wPMecpSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
